export const TICKERS = [
    'TRXUSDT', 'ADAUSDT', 'TONUSDT', 'NEARUSDT',
    'XLMUSDT', 'ALGOUSDT', 'IOTAUSDT', 'ICPUSDT', 'ZILUSDT',
    'SANDUSDT', 'POPUSDT', 'ALCHUSDT', 'GRASSUSDT', 'WCTUSDT', 'PENGUUSDT',
  ];
  